### ISSUE TITLE
MIPS是什么意思

### ISSUE THREAD

**Issue by Runningwater2357** [hymie122/RAG-Survey#3]
“utilizing MIPS for selecting the top-k documents with the highest probability and periodically updating the index” 这里的MIPS是什么

**Comment by HugoZHL** [comment]
这里指 Maximum inner-product search: https://en.wikipedia.org/wiki/Maximum_inner-product_search
这是向量搜索中常用的方法。我们后续会持续优化arxiv文章，感谢指出问题~
