### ISSUE TITLE
RAG综述太多了

### ISSUE THREAD

**Issue by PeterXiaTian** [hymie122/RAG-Survey#4]
国内RAG综述的论文太多了，你这篇相比其他如复旦大学、同济大学等的创新点是什么？

有实践过吗？在检索方面有什么好的idea？

**Comment by hymie122** [comment]
我们和其他文章聚焦的场景不一样，关于这一点我们文章里的related work章节有具体说明。
我们下一步正在探索具体实践以及RAG系统、算法方面的优化，欢迎持续关注我们的后续工作；关于检索方面，具体可以参考我们文章中的Retriever Enhancement部分，看看有没有适合你们任务场景的方法。
